import openpyxl



def label_for_assem(workbook):
    destination_workbook = openpyxl.load_workbook('/Users/maanitmalhan/Documents/IAC_Center/excel-data-iac/files/SNE_IAC_Database.xlsx')
    destination_sheet = destination_workbook['ASSESS']

    destination_sheet['A1'] = 'Assessment ID'
    destination_sheet['B1'] = 'IAC Center Code'
    destination_sheet['C1'] = 'Fiscal Year'
    destination_sheet['D1'] = 'SIC Industrial Classification Code'
    destination_sheet['E1'] = 'NAICS Industrial Classification Code'
    destination_sheet['F1'] = 'US State Abbreviation'
    destination_sheet['G1'] = 'Total Yearly Sales'
    destination_sheet['H1'] = 'Total Number of Employees'
    destination_sheet['I1'] = 'Total Plant of Square Footage'
    destination_sheet['J1'] = 'Type of Products'
    destination_sheet['K1'] = 'Production Level Units'
    destination_sheet['L1'] = 'Total Yearly Production'
    destination_sheet['M1'] = 'Total Yearly Hours of Operation'
    destination_sheet['N1'] = 'Total Number of Recommendations'
    destination_sheet['O1'] = 'Total Yearly Electricity Consumption Cost($)'
    destination_sheet['P1'] = 'Total Yearly Electricity Consumption(kWh)'
    destination_sheet['Q1'] = 'Total Yearly Electricity Demand Charges($)'
    destination_sheet['R1'] = 'Total Yearly Electricity Demand(kW-month-year)'
    destination_sheet['S1'] = 'Total Yearly Electricity Fees'
    destination_sheet['T1'] = 'Total Yearly Natural Gas Consumption Cost($)'
    destination_sheet['U1'] = 'Total Yearly Natural Gas Consumption(MMBtu)'
    destination_sheet['V1'] = 'Total Yearly LPG Consumption Cost($)'
    destination_sheet['W1'] = 'Total Yearly LPG Consumption(MMBtu)'
    destination_sheet['X1'] = 'Total Yearly #1 Fuel Oil Consumption Cost($)'
    destination_sheet['Y1'] = 'Total Yearly #1 Fuel Oil Consumption(MMBtu)'
    destination_sheet['Z1'] = 'Total Yearly #2 Fuel Oil Consumption Cost($)'
    destination_sheet['AA1'] = 'Total Yearly #2 Fuel Oil Consumption(MMBtu)'
    destination_sheet['AB1'] = 'Total Yearly #4 Fuel Oil Consumption Cost($)'
    destination_sheet['AC1'] = 'Total Yearly #4 Fuel Oil Consumption(MMBtu)'
    destination_sheet['AD1'] = 'Total Yearly #5 Fuel Oil Consumption Cost($)'
    destination_sheet['AE1'] = 'Total Yearly #5 Fuel Oil Consumption(MMBtu)'
    destination_sheet['AF1'] = 'Total Yearly #6 Fuel Oil Consumption Cost($)'
    destination_sheet['AG1'] = 'Total Yearly #6 Fuel Oil Consumption(MMBtu)'
    destination_sheet['AH1'] = 'Total Yearly Coal Consumption Cost($)'
    destination_sheet['AI1'] = 'Total Yearly Coal Consumption(MMBtu)'
    destination_sheet['AJ1'] = 'Total Yearly Wood Consumption($)'
    destination_sheet['AK1'] = 'Total Yearly Wood Consumption(MMBtu)'
    destination_sheet['AL1'] = 'Total Yearly Paper Consumption($)'
    destination_sheet['AM1'] = 'Total Yearly Paper Consumption(MMBtu)'
    destination_sheet['AN1'] = 'Total Yearly Other Gas Consumption Cost($)'
    destination_sheet['AO1'] = 'Total Yearly Other Gas Consumption(MMBtu)'
    destination_sheet['AP1'] = 'Total Yearly Other Energy Consumption Cost($)'
    destination_sheet['AQ1'] = 'Total Yearly Other Energy Consumption(MMBtu)'
    destination_sheet['AR1'] = 'Total Yearly Water Consumption Cost($)'
    destination_sheet['AS1'] = 'Total Yearly Water Consumption(TGal)'
    destination_sheet['AT1'] = 'Total Yearly Water Disposals Cost($)'
    destination_sheet['AU1'] = 'Total Yearly Water Disposals(Gal)'
    destination_sheet['AV1'] = 'Total Yearly Other Liquid(Non-Haz) Disposals Cost($)'
    destination_sheet['AW1'] = 'Total Yearly Other Liquid(Non-Haz) Disposals(Gal)'
    destination_sheet['AX1'] = 'Total Yearly Other Liquid(Haz) Disposals Cost($)'
    destination_sheet['AY1'] = 'Total Yearly Other Liquid(Haz) Disposals(Gal)'
    destination_sheet['AZ1'] = 'Total Yearly Other Solid(Non-Haz) Disposals Cost($)'
    destination_sheet['BA1'] = 'Total Yearly Other Solid(Non-Haz) Disposals(lbs)'
    destination_sheet['BB1'] = 'Total Yearly Other Solid(Haz) Disposals Cost($)'
    destination_sheet['BC1'] = 'Total Yearly Other Solid(Haz) Disposals(lbs)'
    destination_sheet['BD1'] = 'Total Yearly Other Gaseous Waste Cost($)'
    destination_sheet['BE1'] = 'Total Yearly Other Gaseous Waste(lbs)'

def label_for_recc(workbook):
    destination_workbook = openpyxl.load_workbook('/Users/maanitmalhan/Documents/IAC_Center/excel-data-iac/files/SNE_IAC_Database.xlsx')
    destination_sheet = destination_workbook['RECC']

    destination_sheet['A1'] = 'Assessment ID + Recommendation ID'
    destination_sheet['B1'] = 'Assessment ID'
    destination_sheet['C1'] = 'Recommendation Number'
    destination_sheet['D1'] = 'Application Code'
    destination_sheet['E1'] = 'IAC Assessment Recommendation Code'
    destination_sheet['F1'] = 'Implementation Status(I = implemented, N = not implemented)'
    destination_sheet['G1'] = 'Total implementation cost'
    destination_sheet['H1'] = 'Primary resource identification code'
    destination_sheet['I1'] = 'Unit Conserved'
    destination_sheet['J1'] = 'Sources Units Conserved'
    destination_sheet['K1'] = 'Cost Savings'
    destination_sheet['L1'] = 'Secondary resource identification code'
    destination_sheet['I1'] = 'Unit Conserved'
    destination_sheet['J1'] = 'Sources Units Conserved'
    destination_sheet['K1'] = 'Cost Savings'
    destination_sheet['H1'] = 'Tertiary resource identification code'
    destination_sheet['I1'] = 'Unit Conserved'
    destination_sheet['J1'] = 'Sources Units Conserved'
    destination_sheet['K1'] = 'Cost Savings'
    destination_sheet['L1'] = 'Quaternary resource identification code'
    destination_sheet['I1'] = 'Unit Conserved'
    destination_sheet['J1'] = 'Sources Units Conserved'
    destination_sheet['K1'] = 'Cost Savings'
    destination_sheet['M1'] = 'Was a rebate Involved(Yes/No)'
    destination_sheet['N1'] = 'Was the recommendation implemented incrementally(Yes/No)'
    destination_sheet['O1'] = 'Fiscal Year'
    destination_sheet['P1'] = 'Capital Component of implementation cost'
    destination_sheet['Q1'] = 'Other Component of implementation cost'
    destination_sheet['R1'] = 'Simple Payback(Years)'
    destination_sheet['S1'] = 'What best practice tools was used(if any)'