import openpyxl

def label_for_assem():
    destination_workbook = openpyxl.load_workbook('/Users/maanitmalhan/Documents/IAC_Center/excel-data-iac/files/SNE_IAC_Database.xlsx')
    destination_sheet = destination_workbook['ASSESS']  

    print("Labeling ASSESS sheet...")  
    destination_sheet['A1'].value = 'Assessment ID'
    destination_sheet['B1'].value = 'IAC Center Code'
    destination_sheet['C1'].value = 'Fiscal Year'
    destination_sheet['D1'].value = 'SIC Industrial Classification Code'
    destination_sheet['E1'].value = 'NAICS Industrial Classification Code'
    destination_sheet['F1'].value = 'US State Abbreviation'
    destination_sheet['G1'].value = 'Total Yearly Sales'
    destination_sheet['H1'].value = 'Total Number of Employees'
    destination_sheet['I1'].value = 'Total Plant of Square Footage'
    destination_sheet['J1'].value = 'Type of Products'
    destination_sheet['K1'].value = 'Production Level Units'
    destination_sheet['L1'].value = 'Total Yearly Production'
    destination_sheet['M1'].value = 'Total Yearly Hours of Operation'
    destination_sheet['N1'].value = 'Total Number of Recommendations'
    destination_sheet['O1'].value = 'Total Yearly Electricity Consumption Cost($)'
    destination_sheet['P1'].value = 'Total Yearly Electricity Consumption(kWh)'
    destination_sheet['Q1'].value = 'Total Yearly Electricity Demand Charges($)'
    destination_sheet['R1'].value = 'Total Yearly Electricity Demand(kW-month-year)'
    destination_sheet['S1'].value = 'Total Yearly Electricity Fees'
    destination_sheet['T1'].value = 'Total Yearly Natural Gas Consumption Cost($)'
    destination_sheet['U1'].value= 'Total Yearly Natural Gas Consumption(MMBtu)'
    destination_sheet['V1'].value= 'Total Yearly LPG Consumption Cost($)'
    destination_sheet['W1'].value= 'Total Yearly LPG Consumption(MMBtu)'
    destination_sheet['X1'].value= 'Total Yearly #1 Fuel Oil Consumption Cost($)'
    destination_sheet['Y1'].value= 'Total Yearly #1 Fuel Oil Consumption(MMBtu)'
    destination_sheet['Z1'].value= 'Total Yearly #2 Fuel Oil Consumption Cost($)'
    destination_sheet['AA1'].value = 'Total Yearly #2 Fuel Oil Consumption(MMBtu)'
    destination_sheet['AB1'].value = 'Total Yearly #4 Fuel Oil Consumption Cost($)'
    destination_sheet['AC1'].value = 'Total Yearly #4 Fuel Oil Consumption(MMBtu)'
    destination_sheet['AD1'].value = 'Total Yearly #5 Fuel Oil Consumption Cost($)'
    destination_sheet['AE1'].value = 'Total Yearly #5 Fuel Oil Consumption(MMBtu)'
    destination_sheet['AF1'].value = 'Total Yearly #6 Fuel Oil Consumption Cost($)'
    destination_sheet['AG1'].value = 'Total Yearly #6 Fuel Oil Consumption(MMBtu)'
    destination_sheet['AH1'].value = 'Total Yearly Coal Consumption Cost($)'
    destination_sheet['AI1'].value = 'Total Yearly Coal Consumption(MMBtu)'
    destination_sheet['AJ1'].value = 'Total Yearly Wood Consumption($)'
    destination_sheet['AK1'].value = 'Total Yearly Wood Consumption(MMBtu)'
    destination_sheet['AL1'].value = 'Total Yearly Paper Consumption($)'
    destination_sheet['AM1'].value = 'Total Yearly Paper Consumption(MMBtu)'
    destination_sheet['AN1'].value = 'Total Yearly Other Gas Consumption Cost($)'
    destination_sheet['AO1'].value = 'Total Yearly Other Gas Consumption(MMBtu)'
    destination_sheet['AP1'].value = 'Total Yearly Other Energy Consumption Cost($)'
    destination_sheet['AQ1'].value = 'Total Yearly Other Energy Consumption(MMBtu)'
    destination_sheet['AR1'].value = 'Total Yearly Water Consumption Cost($)'
    destination_sheet['AS1'].value = 'Total Yearly Water Consumption(TGal)'
    destination_sheet['AT1'].value = 'Total Yearly Water Disposals Cost($)'
    destination_sheet['AU1'].value = 'Total Yearly Water Disposals(Gal)'
    destination_sheet['AV1'].value = 'Total Yearly Other Liquid(Non-Haz) Disposals Cost($)'
    destination_sheet['AW1'].value = 'Total Yearly Other Liquid(Non-Haz) Disposals(Gal)'
    destination_sheet['AX1'].value = 'Total Yearly Other Liquid(Haz) Disposals Cost($)'
    destination_sheet['AY1'].value = 'Total Yearly Other Liquid(Haz) Disposals(Gal)'
    destination_sheet['AZ1'].value = 'Total Yearly Other Solid(Non-Haz) Disposals Cost($)'
    destination_sheet['BA1'].value = 'Total Yearly Other Solid(Non-Haz) Disposals(lbs)'
    destination_sheet['BB1'].value = 'Total Yearly Other Solid(Haz) Disposals Cost($)'
    destination_sheet['BC1'].value = 'Total Yearly Other Solid(Haz) Disposals(lbs)'
    destination_sheet['BD1'].value = 'Total Yearly Other Gaseous Waste Cost($)'
    destination_sheet['BE1'].value = 'Total Yearly Other Gaseous Waste(lbs)'
    destination_workbook.save('/Users/maanitmalhan/Documents/IAC_Center/excel-data-iac/files/SNE_IAC_Database.xlsx')
    print("ASSESS sheet labeled.")

def label_for_recc():
    destination_workbook = openpyxl.load_workbook('/Users/maanitmalhan/Documents/IAC_Center/excel-data-iac/files/SNE_IAC_Database.xlsx')
    destination_sheet = destination_workbook['ASSESS']  
    print("labelling for RECC sheet")
    destination_sheet['A1'].value = 'Assessment ID + Recommendation ID'
    destination_sheet['B1'].value = 'Assessment ID'
    destination_sheet['C1'].value = 'Recommendation Number'
    destination_sheet['D1'].value = 'Application Code'
    destination_sheet['E1'].value = 'IAC Assessment Recommendation Code'
    destination_sheet['F1'].value = 'Implementation Status(I = implemented, N = not implemented)'
    destination_sheet['G1'].value = 'Total implementation cost'
    destination_sheet['H1'].value = 'Primary resource identification code'
    destination_sheet['I1'].value= 'Unit Conserved'
    destination_sheet['J1'].value = 'Sources Units Conserved'
    destination_sheet['K1'].value = 'Cost Savings'
    destination_sheet['L1'].value = 'Secondary resource identification code'
    destination_sheet['I1'].value = 'Unit Conserved'
    destination_sheet['J1'].value = 'Sources Units Conserved'
    destination_sheet['K1'].value = 'Cost Savings'
    destination_sheet['H1'].value = 'Tertiary resource identification code'
    destination_sheet['I1'].value = 'Unit Conserved'
    destination_sheet['J1'].value = 'Sources Units Conserved'
    destination_sheet['K1'].value = 'Cost Savings'
    destination_sheet['L1'].value = 'Quaternary resource identification code'
    destination_sheet['I1'].value = 'Unit Conserved'
    destination_sheet['J1'].value = 'Sources Units Conserved'
    destination_sheet['K1'].value = 'Cost Savings'
    destination_sheet['M1'].value = 'Was a rebate Involved(Yes/No)'
    destination_sheet['N1'].value = 'Was the recommendation implemented incrementally(Yes/No)'
    destination_sheet['O1'].value = 'Fiscal Year'
    destination_sheet['P1'].value = 'Capital Component of implementation cost'
    destination_sheet['Q1'].value = 'Other Component of implementation cost'
    destination_sheet['R1'].value = 'Simple Payback(Years)'
    destination_sheet['S1'].value = 'What best practice tools was used(if any)'
    print("RECC sheet labeled.")
    destination_workbook.save('RECC')



